### ISSUE TITLE
Look into python packages to interact with Telegram

### ISSUE THREAD

**Issue by mpitavidal** [mpitavidal/topo-bot#2]

**Comment by scp062** [comment]
https://pypi.org/project/python-telegram-bot/

looks like what we need
i will install the package and try to create my first bot as a tutorial

**Comment by scp062** [comment]
Happy birthday, @TopologicalQuantumBot !

**Comment by scp062** [comment]
The bot posts to the channel with the address https://t.me/openmajoranachannel now
